# Generated by Django 5.2.7 on 2026-01-23 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('families', '0003_rename_address_if_different_familymember_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='member',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_account', to='families.familymember'),
            preserve_default=False,
        ),
    ]
