# Generated by Django 5.2.7 on 2026-02-10 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_member'),
        ('families', '0007_remove_familymember_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='member',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_account', to='families.familymember'),
        ),
    ]
