# Generated by Django 5.2.7 on 2026-02-28 13:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_invitetoken'),
        ('families', '0015_familymember_is_independent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('username', models.CharField(help_text='Username set by guardian for the new account.', max_length=150)),
                ('temp_password', models.CharField(help_text='Temporary password set by guardian.', max_length=128)),
                ('is_claimed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(help_text='The guardian who generated this claim.', on_delete=django.db.models.deletion.CASCADE, related_name='generated_claims', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(help_text='The managed profile being claimed.', on_delete=django.db.models.deletion.CASCADE, related_name='claim_tokens', to='families.familymember')),
            ],
        ),
    ]
