# Generated by Django 5.2.7 on 2026-01-23 07:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='familymember',
            old_name='address',
            new_name='address_if_different',
        ),
        migrations.RenameField(
            model_name='familymember',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='familymember',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='familymember',
            name='crematory',
        ),
        migrations.RemoveField(
            model_name='familymember',
            name='date_of_death',
        ),
        migrations.RemoveField(
            model_name='familymember',
            name='is_deceased',
        ),
        migrations.RemoveField(
            model_name='familymember',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='familymember',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='familymember',
            name='profile_pic',
        ),
        migrations.RemoveField(
            model_name='familymember',
            name='spouse',
        ),
        migrations.AddField(
            model_name='familymember',
            name='age',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='familymember',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='members/photos/'),
        ),
        migrations.AddField(
            model_name='familymember',
            name='relation',
            field=models.CharField(default='Member', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='familymember',
            name='temp_member_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='familymember',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='blood_group',
            field=models.CharField(default='U', max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='familymember',
            name='church_parish',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='date_of_birth',
            field=models.DateField(default='2000-01-01'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='familymember',
            name='education',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='familymember',
            name='email_id',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='occupation',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='familymember',
            name='place_of_work',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='DeceasedMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age_at_death', models.PositiveIntegerField()),
                ('relation', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('date_of_death', models.DateField()),
                ('crematory', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='deceased/photos/')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deceased', to='families.family')),
            ],
        ),
        migrations.CreateModel(
            name='FamilyMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('family', 'Family'), ('wedding', 'Wedding'), ('achievement', 'Achievement')], max_length=20)),
                ('image', models.ImageField(upload_to='family/gallery/')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='families.family')),
            ],
        ),
    ]
