# Generated by Django 5.2.7 on 2026-01-23 10:02

import django.db.models.deletion
from django.db import migrations, models


import django.utils.timezone

class Migration(migrations.Migration):

    dependencies = [
        ('families', '0002_rename_address_familymember_address_if_different_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='familymember',
            old_name='address_if_different',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='familymember',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RemoveField(
            model_name='familymember',
            name='age',
        ),
        migrations.RemoveField(
            model_name='familymember',
            name='parents',
        ),
        migrations.RemoveField(
            model_name='familymember',
            name='relation',
        ),
        migrations.AddField(
            model_name='familymember',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='familymember',
            name='crematory',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='familymember',
            name='date_of_death',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='familymember',
            name='is_deceased',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='familymember',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='familymember',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='families.familymember'),
        ),
        migrations.AddField(
            model_name='familymember',
            name='spouse',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spouse_ref', to='families.familymember'),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='blood_group',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='church_parish',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='education',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='email_id',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=10),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='occupation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='place_of_work',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='DeceasedMember',
        ),
    ]
