# Generated by Django 5.2.7 on 2026-02-05 00:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0003_rename_address_if_different_familymember_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='familymember',
            old_name='address',
            new_name='address_if_different',
        ),
        migrations.RenameField(
            model_name='familymember',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='familymember',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='familymember',
            name='church_parish',
        ),
        migrations.RemoveField(
            model_name='familymember',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='familymember',
            name='crematory',
        ),
        migrations.RemoveField(
            model_name='familymember',
            name='date_of_death',
        ),
        migrations.RemoveField(
            model_name='familymember',
            name='email_id',
        ),
        migrations.RemoveField(
            model_name='familymember',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='familymember',
            name='is_deceased',
        ),
        migrations.RemoveField(
            model_name='familymember',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='familymember',
            name='nickname',
        ),
        migrations.RemoveField(
            model_name='familymember',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='familymember',
            name='phone_no',
        ),
        migrations.RemoveField(
            model_name='familymember',
            name='spouse',
        ),
        migrations.AddField(
            model_name='familymember',
            name='age',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='familymember',
            name='parents',
            field=models.ManyToManyField(blank=True, related_name='children', to='families.familymember'),
        ),
        migrations.AddField(
            model_name='familymember',
            name='relation',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='familymember',
            name='blood_group',
            field=models.CharField(default=0, max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='familymember',
            name='date_of_birth',
            field=models.DateField(default='2000-01-01'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='familymember',
            name='education',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='familymember',
            name='occupation',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='familymember',
            name='place_of_work',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='DeceasedMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age_at_death', models.PositiveIntegerField()),
                ('relation', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('date_of_death', models.DateField()),
                ('crematory', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='deceased/photos/')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deceased', to='families.family')),
            ],
        ),
    ]
