# Generated by Django 5.2.7 on 2026-02-07 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0005_rename_address_if_different_familymember_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='familymember',
            old_name='address',
            new_name='address_if_different',
        ),
        migrations.RemoveField(
            model_name='familymember',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='familymember',
            name='church_parish',
        ),
        migrations.RemoveField(
            model_name='familymember',
            name='date_of_death',
        ),
        migrations.RemoveField(
            model_name='familymember',
            name='email_id',
        ),
        migrations.RemoveField(
            model_name='familymember',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='familymember',
            name='is_deceased',
        ),
        migrations.RemoveField(
            model_name='familymember',
            name='nickname',
        ),
        migrations.RemoveField(
            model_name='familymember',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='familymember',
            name='phone_no',
        ),
        migrations.RemoveField(
            model_name='familymember',
            name='spouse',
        ),
    ]
