# Generated by Django 5.2.7 on 2026-02-10 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0006_rename_address_familymember_address_if_different_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familymember',
            name='user',
        ),
    ]
