# Generated by Django 5.2.7 on 2026-02-12 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0007_remove_familymember_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymember',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='familymember',
            name='church_parish',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='familymember',
            name='email_id',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='familymember',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=1),
        ),
        migrations.AddField(
            model_name='familymember',
            name='phone_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
