# Generated by Django 5.2.7 on 2026-02-26 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0009_familymember_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymember',
            name='blood_group',
            field=models.CharField(max_length=10),
        ),
    ]
