# Generated by Django 5.2.7 on 2026-02-26 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0010_alter_familymember_blood_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymember',
            name='nickname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
