# Generated by Django 5.2.7 on 2026-02-26 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0011_familymember_nickname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(choices=[('Spouse', 'Spouse'), ('Aunt', 'Aunt'), ('Uncle', 'Uncle'), ('Cousin', 'Cousin'), ('Grandparent', 'Grandparent'), ('Sibling', 'Sibling'), ('Father', 'Father'), ('Mother', 'Mother'), ('Other', 'Other')], max_length=20)),
                ('from_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_from', to='families.familymember')),
                ('to_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_to', to='families.familymember')),
            ],
            options={
                'unique_together': {('from_member', 'to_member', 'relation_type')},
            },
        ),
    ]
