# Generated by Django 5.2.7 on 2026-02-26 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0012_relationship'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymember',
            name='is_deceased',
            field=models.BooleanField(default=False),
        ),
    ]
