# Generated by Django 5.2.7 on 2026-02-28 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0014_alter_familymember_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymember',
            name='is_independent',
            field=models.BooleanField(default=False, help_text='When True, the creator/guardian loses write access and the profile owner has full control.'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='relation_type',
            field=models.CharField(choices=[('PARENT', 'Parent'), ('SPOUSE', 'Spouse'), ('SIBLING', 'Sibling')], max_length=20),
        ),
    ]
