# Generated by Django 5.2.7 on 2026-02-28 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0016_data_migrate_relationships_and_independence'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymember',
            name='date_of_death',
            field=models.DateField(blank=True, null=True),
        ),
    ]
