# Generated by Django 5.2.7 on 2026-02-28 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0017_familymember_date_of_death'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymember',
            name='relation',
            field=models.CharField(choices=[('Head', 'Head'), ('Spouse', 'Spouse'), ('Father', 'Father'), ('Mother', 'Mother'), ('Son', 'Son'), ('Daughter', 'Daughter'), ('Brother', 'Brother'), ('Sister', 'Sister'), ('Grandfather', 'Grandfather'), ('Grandmother', 'Grandmother'), ('Grandson', 'Grandson'), ('Granddaughter', 'Granddaughter'), ('Uncle', 'Uncle'), ('Aunt', 'Aunt'), ('Nephew', 'Nephew'), ('Niece', 'Niece'), ('Cousin', 'Cousin'), ('Father-in-law', 'Father-in-law'), ('Mother-in-law', 'Mother-in-law'), ('Son-in-law', 'Son-in-law'), ('Daughter-in-law', 'Daughter-in-law'), ('Brother-in-law', 'Brother-in-law'), ('Sister-in-law', 'Sister-in-law'), ('Other', 'Other')], default='Other', max_length=50),
        ),
    ]
