# Generated by Django 5.2.7 on 2026-02-28 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0018_alter_familymember_relation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationship',
            name='relation_type',
            field=models.CharField(choices=[('PARENT', 'Parent'), ('CHILD', 'Child'), ('SPOUSE', 'Spouse'), ('SIBLING', 'Sibling'), ('GRANDPARENT', 'Grandparent'), ('GRANDCHILD', 'Grandchild'), ('UNCLE', 'Uncle'), ('AUNT', 'Aunt'), ('NEPHEW', 'Nephew'), ('NIECE', 'Niece'), ('COUSIN', 'Cousin'), ('FATHER_IN_LAW', 'Father-in-law'), ('MOTHER_IN_LAW', 'Mother-in-law'), ('SON_IN_LAW', 'Son-in-law'), ('DAUGHTER_IN_LAW', 'Daughter-in-law'), ('BROTHER_IN_LAW', 'Brother-in-law'), ('SISTER_IN_LAW', 'Sister-in-law'), ('OTHER', 'Other')], max_length=30),
        ),
    ]
