# Generated by Django 5.2.7 on 2026-03-01 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0020_alter_relationship_relation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationship',
            name='relation_type',
            field=models.CharField(choices=[('Father', 'Father'), ('Mother', 'Mother'), ('Son', 'Son'), ('Daughter', 'Daughter'), ('Spouse', 'Spouse'), ('Brother', 'Brother'), ('Sister', 'Sister'), ('Grandfather', 'Grandfather'), ('Grandmother', 'Grandmother'), ('Paternal Grandfather', 'Paternal Grandfather'), ('Paternal Grandmother', 'Paternal Grandmother'), ('Maternal Grandfather', 'Maternal Grandfather'), ('Maternal Grandmother', 'Maternal Grandmother'), ('Grandson', 'Grandson'), ('Granddaughter', 'Granddaughter'), ('Uncle', 'Uncle'), ('Aunt', 'Aunt'), ('Nephew', 'Nephew'), ('Niece', 'Niece'), ('Cousin', 'Cousin'), ('Father-in-law', 'Father-in-law'), ('Mother-in-law', 'Mother-in-law'), ('Son-in-law', 'Son-in-law'), ('Daughter-in-law', 'Daughter-in-law'), ('Brother-in-law', 'Brother-in-law'), ('Sister-in-law', 'Sister-in-law'), ('Other', 'Other')], max_length=50),
        ),
    ]
