# Generated by Django 5.2.7 on 2026-02-16 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
