# Generated by Django 5.2.7 on 2026-02-15 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_post_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_kudumbayogam',
            field=models.BooleanField(default=False),
        ),
    ]
